#pragma once
#include "CoreMinimal.h"
#include "EHbkPlayerRDGrowthType.generated.h"

UENUM(BlueprintType)
enum class EHbkPlayerRDGrowthType : uint8 {
    None,
    GrowthAddItem,
    LifeUp,
    GaugeUp,
    LifeTankUp,
    OverchargeUp,
    SpecialAttack,
    GrowthParam,
    AttackUp_Normal,
    AttackUp_SPA,
    AttackUp_Partner,
    DamageUp_ToTough,
    DefenseUp,
    AutoRecovery,
    FinishBattleDropHealth,
    BatteryUp,
    ParryBattery,
    PartnerCoolTimeDown_P,
    PartnerCoolTimeDown_M,
    PartnerCoolTimeDown_K,
    P_DownTimeUp,
    P_ElectricEnemy,
    K_FloatingTimeUp,
    K_DebuffTimeUp,
    M_WaveRangeUp,
    M_LuckyShieldDamage,
    ShowEnemyHealth,
    ParryRecovery,
    PlayerBuff,
    Vampire,
    StealBattery,
    ButterflyEffect,
    DeathTouch,
    Aikido,
    Whirlwind,
    ForceBlowOff,
    Drone,
    PlayerDebuff,
    Filter,
    GroundPoison,
    AirPoison,
    DeathExplosion,
    CrossCounter,
    BeamDamageUp,
    BurnDamageUp,
    CancelItemAbsorb,
    ReflectDamage,
    EnemyAttacks,
    SlowPartners,
    HighRiskAndReturn,
};

