#pragma once
#include "CoreMinimal.h"
#include "EHbkPhotoMenu_DataType.generated.h"

UENUM(BlueprintType)
enum class EHbkPhotoMenu_DataType : uint8 {
    None,
    Camera_FOV,
    Camera_Yaw,
    Camera_DOF,
    Camera_Blur,
    Camera_Focus,
    Camera_Vignette,
    Camera_Irosyusa,
    Camera_Sharp,
    Camera_Filmgrain,
    Camera_Distortion,
    Camera_IrosyusaSwitch,
    Camera_OthersSwitch,
    Filter_Switch,
    Filter_Preset,
    Filter_TotalBlend,
    Filter_ApplyType,
    Filter_Hue,
    Filter_Chroma,
    Filter_Brigntness,
    Filter_Luminance,
    Filter_ColorFilterType,
    Filter_ColorFilterBlend,
    Filter_LineBlend,
    Filter_LineDrawType,
    Filter_VHSPixelBlend,
    Filter_VHSPixelSize,
    Filter_VHSScanLineBlend,
    Filter_VHSScanLineSize,
    Filter_PrintFilterType,
    Filter_PrintFilterBlend,
    Filter_PrintFilterSize,
    Filter_TextureFilterType,
    Filter_TextureFilterBlend,
    Pose_View,
    Pose_Pose,
    Pose_Facial,
    Pose_Yaw,
    Pose_LocationX,
    Pose_LocationY,
    Pose_LocationZ,
    Frame,
    Wallpaper,
    Sticker,
};

