#pragma once
#include "CoreMinimal.h"
#include "EHbkTalkFaceType.generated.h"

UENUM(BlueprintType)
enum class EHbkTalkFaceType : uint8 {
    TFACE_None,
    TFACE_Chai,
    TFACE_Chai_Shark,
    TFACE_Peppermint,
    TFACE_Macaron,
    TFACE_CNMN,
    TFACE_Korsica_PT,
    TFACE_Korsica,
    TFACE_Rekka,
    TFACE_Zanzo,
    TFACE_Mimosa,
    TFACE_Roquefort_A,
    TFACE_Roquefort_B,
    TFACE_KALE,
    TFACE_TEC78,
    TFACE_TEC78_B,
    TFACE_TEC78_OL,
    TFACE_Roxanne,
    TFACE_CleaningBot_A,
    TFACE_CleaningBot_B,
    TFACE_CleaningBot_C,
    TFACE_CleaningBot_D,
    TFACE_ProgrammerBot,
    TFACE_AsistantBot,
    TFACE_SPECTRA,
    TFACE_SPEAKER,
    TFACE_HintBot,
    TFACE_Saber,
    TFACE_Gunner,
    TFACE_EliteSaber,
    TFACE_BubbleElite,
    TFACE_Centaur,
    TFACE_Samurai,
    TFACE_SamuraiChef,
    TFACE_Blaze,
    TFACE_ChurrascoSaber,
    TFACE_FlameThrower,
    TFACE_TanningSaber,
    TFACE_SEB,
    TFACE_JSF,
    TFACE_WK_Normal_np3000,
    TFACE_WK_Normal_np3010,
    TFACE_WK_Normal_np3020,
    TFACE_WK_Normal_np3030,
    TFACE_WK_Normal_np3040,
    TFACE_WK_Normal_np3050,
    TFACE_WK_Drill_np3100,
    TFACE_WK_Drill_np3110,
    TFACE_WK_Drill_np3120,
    TFACE_WK_Drill_np3130,
    TFACE_WK_Stretch_np3200,
    TFACE_WK_Stretch_np3210,
    TFACE_WK_Stretch_np3220,
    TFACE_WK_Stretch_np3230,
    TFACE_WK_MagicHand_np3300,
    TFACE_808,
    TFACE_Chai_Surgery,
    TFACE_NPC_GraffitiRobot,
    TFACE_NPC_RobotD_Museum,
    TFACE_NPC_TestRobot,
};

