#pragma once
#include "CoreMinimal.h"
#include "EHbkTitleMenuFlowMainState.generated.h"

UENUM(BlueprintType)
enum class EHbkTitleMenuFlowMainState : uint8 {
    Start,
    NoticeScreenStart = Start,
    NoticeScreen,
    TitleStart,
    TitleUIStart,
    Title,
    FirstSettingStart,
    FirstSetting,
    TopMenuStart,
    TopMenuStartWait,
    TopMenuUIStart,
    TopMenuUIStart_Boot,
    TopMenu,
    NewGame_SelectSlotStart,
    NewGame_SelectSlotStartWait,
    NewGame_SelectSlotUIStart,
    NewGame_SelectSlot,
    NewGame_DifficultySelectStart,
    NewGame_DifficultySelect,
    NewGame_AccessibilitySettingStart,
    NewGame_AccessibilitySetting,
    NewGame_OpEvStart,
    NewGame_OpEvCrossFadeCap,
    NewGame_OpEvCrossFade,
    NewGame_OpEvCsStart,
    NewGame_OpEvCs,
    NewGame_OpEvMovieStart,
    NewGame_OpEvMovie,
    NewGame_GotoOPWait,
    Continue_SelectSlotStart,
    Continue_SelectSlotStartWait,
    Continue_SelectSlotUIStart,
    Continue_SelectSlot,
    Continue_GotoLoad,
    Continue_GotoLoadWait,
    StageSelect_Start,
    StageSelect,
    Option_Start,
    Option_StartWait,
    Option_UIStart,
    Option,
    BNetStart,
    BNet,
    CreditStart,
    Credit,
    QuitGameStart,
    QuitGame,
    Error,
    Max,
};

