#pragma once
#include "CoreMinimal.h"
#include "TngSoundGoogleTTSVoiceName.generated.h"

UENUM(BlueprintType)
enum class TngSoundGoogleTTSVoiceName : uint8 {
    nl_NL_Standard_A,
    nl_NL_Wavenet_A,
    en_AU_Standard_A,
    en_AU_Standard_B,
    en_AU_Standard_C,
    en_AU_Standard_D,
    en_AU_Wavenet_A,
    en_AU_Wavenet_B,
    en_AU_Wavenet_C,
    en_AU_Wavenet_D,
    en_GB_Standard_A,
    en_GB_Standard_B,
    en_GB_Standard_C,
    en_GB_Standard_D,
    en_GB_Wavenet_A,
    en_GB_Wavenet_B,
    en_GB_Wavenet_C,
    en_GB_Wavenet_D,
    en_US_Standard_B,
    en_US_Standard_C,
    en_US_Standard_D,
    en_US_Standard_E,
    en_US_Wavenet_A,
    en_US_Wavenet_B,
    en_US_Wavenet_C,
    en_US_Wavenet_D,
    en_US_Wavenet_E,
    en_US_Wavenet_F,
    fr_FR_Standard_A,
    fr_FR_Standard_B,
    fr_FR_Standard_C,
    fr_FR_Standard_D,
    fr_FR_Wavenet_A,
    fr_FR_Wavenet_B,
    fr_FR_Wavenet_C,
    fr_FR_Wavenet_D,
    fr_CA_Standard_A,
    fr_CA_Standard_B,
    fr_CA_Standard_C,
    fr_CA_Standard_D,
    de_DE_Standard_A,
    de_DE_Standard_B,
    de_DE_Wavenet_A,
    de_DE_Wavenet_B,
    de_DE_Wavenet_C,
    de_DE_Wavenet_D,
    it_IT_Standard_A,
    it_IT_Wavenet_A,
    ja_JP_Standard_A,
    ja_JP_Wavenet_A,
    ko_KR_Standard_A,
    ko_KR_Wavenet_A,
    pt_BR_Standard_A,
    es_ES_Standard_A,
    sv_SE_Standard_A,
    tr_TR_Standard_A,
};

